### ISSUE TITLE
과제 개요 및 2023년 계획

### ISSUE THREAD

**Issue by HyunChaeJung** [HCJung-jbnu/ROMS-TOPAZ#7]
### 3.5~3.6년 탄소과제 (목표)
- 동아시아 해역의 해양 탄소순환 모델링
- 해양 생지화학 반응이 고려된 탄소순환, 동아시아 해역의 탄소흡수율
- 미래기후 시나리오에 따른 해양의 탄소변환이 어떻게 변화할 것인가?
- 내년 1월부터 시작, 3년후...
- 2023년이 단계 평가, 중요함!

### 모델 개발 목표
- ROMS + Fennel 기존
- ROMS + TOPAZ <- 2023년???
~~- NEMO + TOPAZ~~
- 각 모델의 장단점 비교 분석...

**Comment by HyunChaeJung** [comment]
### 할일
~~- MOM-TOPAZ 컴파일/수행~~
~~- ROMS + Fennel 접합 구조 분석~~
- ROMS + TOPAZ 접합
- TOPAZ 부족한 부분 업그레이드(output, river runoff.....) <- MOM-TOPAZ 분석 결과 활용
- NEMO regional version 확인 -> 컴파일/수행 테스트 -> NEMO-TOPAZ regional version 개발

**Comment by HyunChaeJung** [comment]
### ROMS-TOPAZ 접합 준비
~~1. ROMS의 init, boudary data 생산 도구 + MOM-TOPAZ 적용 -> 자료 생산~~

2. 생산한 MOM-TOPAZ의 init, boundary data를 ROMS read -> 모델 내 적용( OCEAN%t 의 bio 변수에 적용)

3. OCEAN%t 에 TOPAZ 예단 변수 연결

4. TOPAZ init 과정 접합, 각종 surface flux 데이터 연결

5. TOPAZ column physics 연결, 필요한 해양 물리변수 ROMS로부터 전달

6. ROMS output 모듈 분석 및 TOPAZ 예단/진단 변수 연결

7. TOPAZ 네임리스트 구성 및 연결

8. TOPAZ chlorophyll에 의한 optic 과정 구현

9. TOPAZ 고도화
```
Topaz init을 초기화(디컴포지션 되지 않는 부분)에 넣기….최적화 부분의 문제.. 코어수가 늘어나면서 최적화 부분에서 대기시간이 길어지는 문제가 발생하고 있음.
ocean_coupler & ocean_ice
runoff 어떻게 계산?? - input 자료가 있는가???
topaz & air-sea flux restart 파일 생성되도록
topaz의 다양한 진단변수 나오는것 적용
pCO2 namelist_topaz_ref에 적용
nemo-topaz의 surface flux 자료의 유닛이 잘못들어가 있음. mol/m2/s로 변경 필요
```

**Comment by HyunChaeJung** [comment]
### 제주대 요청사항 및 질문
~~- model setting 및 namelist 정보(영역, vertical coordinate 정보 등)~~
~~- model compile 옵션 중에서 define, varinfo.dat(변수 테이블) 문의 (헤더파일 *.h)~~
~~- init, boundary 자료 생성 방법(tool 문의)~~
~~- MOM-TOPAZ init, boundary data (daily?)생성해야 됨. 지형자료도?~~
~~- 김태균 박사님이 사용하시는 도구가 있다고 함.~~
~~- MOM-TOPAZ의 자료로 init, boundary data 생산하려 하는데 MOM-TOPAZ의 저해상도 VS ROMS의 고해상도 차이가 문제가 발생할 우려는 없는가?~~

**Comment by HCJung-jbnu** [comment]
## 2023. 04월
- TOPAZ 모듈 개선(고도화) : MOM5의 부속 파일(input.nml, diag_table 등) 필요로 하지 않도록 코드 수정
- TOPAZ의 dry/wet deposition data, ROMS의 forcing 코드에 적용(get_data.F90, set_data.F90, mod_forcing.F90 등...)
- MOM5-TOPAZ, ROMS-FENNEL의 river runoff 분석 중...

**Comment by HCJung-jbnu** [comment]
### 제주대와 논의 사항
- Hz 와 z_w, z_r 계산중 어느것?
- 무광층 몇 미터?
- river runoff 어떻게?

**Comment by HCJung-jbnu** [comment]
### 앞으로 할일
- ROMS-TOPAZ 주석 및 코드 정리
- 앞으로 연구내용 논의(WITH대혁)
- ROMS-COBALT 논문 정독
