### ISSUE TITLE
TOPAZ runoff 추적

### ISSUE THREAD

**Issue by HyunChaeJung** [HCJung-jbnu/ROMS-TOPAZ#9]

**Comment by HyunChaeJung** [comment]
### TOPAZ river runoff 추적
- src/mom5/ocean_core/ocean_sbc.F90
```
   real, dimension(isd:ied,jsd:jed) :: runoff        ! mass flux of liquid river runoff
```
- src/mom5/ocean_bgc/ocean_generic_tracer.F90
```
     !Fill in T_prog(n)%runoff_tracer_flux
     T_prog(g_tracer_index)%runoff_tracer_flux = T_prog(g_tracer_index)%trunoff * runoff
```
- src/mom5/ocean_core/ocean_types.F90
```
     real, dimension(isd:ied,jsd:jed)      :: trunoff          ! tracer concentration in liquid runoff from land
     real, dimension(isd:ied,jsd:jed)      :: tcalving       ! tracer concentration in frozen runoff from land (e.g., calving ice)
```
- src/ocean_shared/generic_tracers/generic_tracer_utils.F90
```
  subroutine g_tracer_coupler_get(g_tracer_list,IOB_struc)
       if(g_tracer%flux_runoff) then
          temp_array=0.0
          call extract_coupler_values(BC_struc  =IOB_struc, &
               BC_index  =g_tracer%flux_runoff_ind, &
               BC_element=ind_flux,                 &
               array_out =temp_array,               &
               conversion=1.0,                      &
               ilb=g_tracer_com%isd,jlb=g_tracer_com%jsd,&
               is=g_tracer_com%isc, ie=g_tracer_com%iec, &
               js=g_tracer_com%jsc, je=g_tracer_com%jec)

          call g_tracer_set_values(g_tracer,g_tracer%name,'trunoff',temp_array,&
               g_tracer_com%isd,g_tracer_com%jsd)
       endif
```

**Comment by synim0816** [comment]
### TOPAZ runoff

- src/shared/coupler/atmos_ocean_fluxed.F90 : subroutine atmos_ocean_fluxed_calc
  - ![image](https://user-images.githubusercontent.com/99166328/229400571-9123607f-245d-4cbb-a368-02717102580c.png)

- src/coupler/flux_exchange.F90 : subroutine sfc_boundary_layer
  - ![image](https://user-images.githubusercontent.com/99166328/229400702-e4e04d2f-7e6f-4f94-837e-283a488c1e12.png)

**Comment by HyunChaeJung** [comment]
- src/coupler/flux_exchange.F90 : subroutine sfc_boundary_layer
```
subroutine flux_down_from_atmos (Time, Atm, Land, Ice, &
     Atmos_boundary, Land_boundary, Ice_boundary )
....
  do tr = 1,n_exch_tr
     where(ex_avail)
        ex_gamma   =  1.0 / (1.0 - ex_dtmass*(ex_dflux_tr(:,tr) + ex_dfdtr_atm(:,tr)))

        ex_e_tr_n(:,tr)      =  ex_dtmass*ex_dfdtr_surf(:,tr)*ex_gamma
        ex_f_tr_delt_n(:,tr) = (ex_delta_tr(:,tr)+ex_dtmass*ex_flux_tr(:,tr))*ex_gamma

        ex_flux_tr(:,tr)     =  ex_flux_tr(:,tr) + ex_dfdtr_atm(:,tr)*ex_f_tr_delt_n(:,tr)
        ex_dfdtr_surf(:,tr)  =  ex_dfdtr_surf(:,tr) + ex_dfdtr_atm(:,tr)*ex_e_tr_n(:,tr)
     endwhere
  enddo
....
  Land_boundary%tr_flux(:,:,:,:) = 0.0
  Land_boundary%dfdtr(:,:,:,:) = 0.0
  do tr = 1,n_exch_tr
     n = tr_table(tr)%lnd
     if(n /= NO_TRACER ) then
        call get_from_xgrid (Land_boundary%tr_flux(:,:,:,n), 'LND', ex_flux_tr(:,tr), xmap_sfc)
        call get_from_xgrid (Land_boundary%dfdtr(:,:,:,n),   'LND', ex_dfdtr_surf(:,tr), xmap_sfc)
#ifdef SCM
        if (do_specified_land .and. do_specified_flux .and. tr.eq.isphum) then
          call get_from_xgrid (Land_boundary%dfdtr(:,:,:,n),   'LND', ex_dedq_surf_forland(:), xmap_sfc)
        endif
#endif
     endif
  enddo
```
- get_from_xgrid : Sums data from exchange grid to model grid.
- put_from_xgrid : Scatters data from model grid onto exchange grid.

**Comment by synim0816** [comment]
### src/coupler/coupler_main.F90 - coupler_init
- call read_data(filename, fieldname, Ice%ocean_fluxes%bc(n)%field(m)%values, Ice%domain)
  - [runoff_변수_분석3.pdf](https://github.com/HyunChaeJung/ROMS-NEMO-TOPAZ/files/11144854/runoff_._.3.pdf)

**Comment by HCJung-jbnu** [comment]
~/Models/MOM5-TOPAZ/src/coupler$ vi flux_exchange.F90
subroutine sfc_boundary_layer ( dt, Time, Atm, Land, Ice, Land_Ice_Atmos_Boundary )

<-------여기서 deposition data 읽어서 가는듯.
! data override for co2 to be passed to ocean (co2_flux_pcair_atm)
! atmos_co2.F90 already called: converts tr_bot passed to ocean via gas_flux
! from moist mmr to dry vmr.
  do n = 1, atm%fields%num_bcs  !{
    do m = 1, atm%fields%bc(n)%num_fields  !{
      call data_override('ATM', atm%fields%bc(n)%field(m)%name,      &
           atm%fields%bc(n)%field(m)%values, Time, override = atm%fields%bc(n)%field(m)%override)
      ex_gas_fields_atm%bc(n)%field(m)%override = atm%fields%bc(n)%field(m)%override
    enddo  !} m
  enddo  !} n
  do n = 1, atm%fields%num_bcs  !{
     if (atm%fields%bc(n)%use_atm_pressure) then  !{
        if (.not. atm%fields%bc(n)%field(ind_psurf)%override) then  !{
           atm%fields%bc(n)%field(ind_psurf)%values = Atm%p_surf
        endif  !}
     endif  !}
  enddo  !} n


<---------- 여기서 위에서 읽은 dop data(Atm%fields%bc(n)%field(m)%values) -> ex_gas_fields_atm%bc(n)%field(m)%values
  do n = 1, Atm%fields%num_bcs  !{
    do m = 1, Atm%fields%bc(n)%num_fields  !{
      call put_to_xgrid (Atm%fields%bc(n)%field(m)%values, 'ATM',            &
           ex_gas_fields_atm%bc(n)%field(m)%values, xmap_sfc, remap_method=remap_method, complete=.false.)
    enddo  !} m
  enddo  !} n


<------------- 여기서 air-sea flux, wet/dry dep, runoff flux 등등을 계산함
! Combine explicit ocean flux and implicit land flux of extra flux fields.

  ! Calculate ocean explicit flux here

  call atmos_ocean_fluxes_calc(ex_gas_fields_atm, ex_gas_fields_ice, ex_gas_fluxes, ex_seawater)

**Comment by HCJung-jbnu** [comment]
### TOPAZ runoff 계산
```
      ! water flux in (kg/m^3)*(m/s) from liquid runoff and calving land ice
      do j = jsc_bnd,jec_bnd
         do i = isc_bnd,iec_bnd
            ii = i + i_shift
            jj = j + j_shift
            runoff(ii,jj)  = Ice_ocean_boundary%runoff(i,j)*Grd%tmask(ii,jj,1)
            calving(ii,jj) = Ice_ocean_boundary%calving(i,j)*Grd%tmask(ii,jj,1)
         enddo
      enddo
      if(use_ideal_runoff) then
          do j=jsc,jec
             do i=isc,iec
                runoff(i,j)  = runoff(i,j)  + ideal_runoff(i,j)
             enddo
          enddo
      endif
      if(use_ideal_calving) then
          do j=jsc,jec
             do i=isc,iec
                calving(i,j) = calving(i,j) + ideal_calving(i,j)
             enddo
          enddo
      endif
      if(runoffspread)  call spread_river_horz(runoff)
      if(calvingspread) call spread_river_horz(calving)

      ! river=runoff+calving is the water mass flux
      ! entering ocean, other than through pme.
      ! calving is immediately melted, so it is appropriate
      ! to add it to runoff for purposes of getting a mass
      ! flux of liquid, from land, into the ocean.
      if(waterflux_tavg) then
          do j=jsc,jec
             do i=isc,iec
                river(i,j)       = 0.5*river_taum1(i,j)
                river_taum1(i,j) = runoff(i,j) + calving(i,j)
                river(i,j)       = river(i,j) + 0.5*river_taum1(i,j)
             enddo
          enddo
      else
          do j=jsc,jec
             do i=isc,iec
                river(i,j) = runoff(i,j) + calving(i,j)
             enddo
          enddo
      endif
```

**Comment by HCJung-jbnu** [comment]
## Runoff 단위
- TOPAZ 변수 단위 Mol/kg - river runoff 단위 Mol/m3
